### PR TITLE
2023.9.1: Vertical scroll of screen

### PR DESCRIPTION
**Pull request by andrewjswan**
Adds the ability to enable screen switching using vertical scrolling.
```
 ehmtxv2:
  id: rgb8x32
...
  vertical_scroll: true
...
```

### CODE REVIEW

**Comment by chertvl** [comment]
Looks great, thanks!
Such small decorations make the watch more lively, dynamic and enjoyable :)

I like that there is no animation when you remove the screen. There is animation only when the screen is placed further in the queue. Very intuitive as to whether or not this screen is worth waiting for again. If he left smoothly, he will return :)

**Comment by lubeda** [comment]
Hi, 
i updated my test environment and now, for the first time, I test your PRs before merging. I found a bug. The scroll for the icon_screens works really great, but my `id(rgb8x32).icon_clock("emptycal|day#0",1440,10)` doesn't work. When the clock is to be displayed I see nothing, only for the last ticks I see how the clock is scrolling down.

**Comment by andrewjswan** [comment]
> but my `id(rgb8x32).icon_clock("emptycal|day#0",1440,10)` doesn't work.

Very strange, @chertvl  had such a problem yesterday, but it was fixed in the [commit](https://github.com/lubeda/EspHoMaTriXv2/pull/159/commits/e7444e3d259676dc4cca56708713f71738c0b2a5). Do you have only one of these screens in your config and that's it? I.e. right at startup one screen and immediately we get this problem?

**Comment by andrewjswan** [comment]
> edit: icon_date works fine!

Even stranger, the rendering mechanism for these screens is the same.
https://github.com/andrewjswan/EspHoMaTriXv2/blob/2023.9.1-Vertical_scroll_of_screen/components/ehmtxv2/EHMTX_queue.cpp#L584-L730

**Comment by andrewjswan** [comment]
> When the clock is to be displayed I see nothing, only for the last ticks I see how the clock is scrolling down.

This is possible in theory if scroll_reset is less than 8, but by the code it is impossible.

**Comment by lubeda** [comment]
icon_date and icon_clock don't make the difference, it is the position in the queue. If icon_date or icon_clock is at the first position in the queue, it has the bug. If e.g. icon_screen is in the first position, everything works fine.

**Comment by lubeda** [comment]
This works:

```
  on_empty_queue:
    then:
      - homeassistant.event:
          event: esphome.ehmtx_empty_queue
      - lambda: |-
          id(rgb8x32).set_infotext_color(20,20,20,20,20,20,true,1);
          id(rgb8x32).icon_screen("door","Hallo",2,10);
          id(rgb8x32).icon_date("emptycal|day#0",1440,10);      
```

this not:
````
  on_empty_queue:
    then:
      - homeassistant.event:
          event: esphome.ehmtx_empty_queue
      - lambda: |-
          id(rgb8x32).set_infotext_color(20,20,20,20,20,20,true,1);
          id(rgb8x32).icon_date("emptycal|day#0",1440,10);
          id(rgb8x32).icon_screen("door","Hallo",2,10);
```

**Comment by andrewjswan** [comment]
> icon_date and icon_clock don't make the difference, it is the position in the queue. If icon_date or icon_clock is at the first position in the queue, it has the bug. If e.g. icon_screen is in the first position, everything works fine.

Do you have a sample config? So I can replicate it for myself?

**Comment by andrewjswan** [comment]
> this not:

Thanks! I'll check it out while I convert it to a draft...

**Comment by andrewjswan** [comment]
> this not:

Nothing at startup (on_start trigger)? Or is it the same there?

**Comment by andrewjswan** [comment]
I found ...

**Comment by andrewjswan** [comment]
@lubeda Can you check?

**Comment by andrewjswan** [comment]
> but the effect doesn't look so good on

Do you mean that the icon comes from the top separately, and the long text comes sort of from the top right corner? And then the icon goes down and the text comes in with it? 
I can probably redo it, but then the effect of vertical scrolling is lost.

**Comment by andrewjswan** [comment]
> I don't know if it makes sense to fix it

I think not, after all it is vertical scrolling, some will like it, some will not, but everyone can choose for themselves.

**Pull request merged**
