### PR TITLE
2023.9.1: Add Bitmap Stack screen

### PR DESCRIPTION
**Pull request by andrewjswan**
https://github.com/lubeda/EspHoMaTriXv2/issues/139

### CODE REVIEW

**Comment by lubeda** [comment]
What about the readme? Why did you change calc scroll time?

**Comment by andrewjswan** [comment]
I dont change, only add new for icons
```
    void calc_scroll_time(std::string text, uint16_t screen_time);
    void calc_scroll_time(uint8_t icon_count, uint16_t screen_time);
```
Readme updated ...

**Comment by lubeda** [comment]
Hi, its a nice effect but the `|two` "parameter" isn't a clean way to pass parameters and the functionality isn't described in the readme.

**Comment by andrewjswan** [comment]
I added 2 examples at the bottom of the Readme, I just don't quite understand how to describe it clearly, should see the effect working on the 1,2,3 icon.

**Pull request merged**
