### PR TITLE
2023.9.1-117: Add a pseudo icon - blank

### PR DESCRIPTION
**Pull request by andrewjswan**
https://github.com/lubeda/EspHoMaTriXv2/issues/117

### CODE REVIEW

**Comment by andrewjswan** [comment]
I reworked the logic a bit, built a generic branch for the test, from 2023.9.1 + PR 118, 119 ... It works without degradation.

**Comment by andrewjswan** [comment]
4 days, no problems, everything is stable in all modes.

**Comment by lubeda** [comment]
Why -1 for the blank icon wouldn't ID 0 more natural?

**Comment by andrewjswan** [comment]
> Why -1 for the blank icon wouldn't ID 0 more natural?

-1 was the original version, it failed, the working and final version is MAXICONS + 1

**Comment by andrewjswan** [comment]
@lubeda look - https://github.com/lubeda/EspHoMaTriXv2/pull/118/files#diff-345f4882a9621cc8a04520b628475a419357f3b98b092260e4749d646698ab16R24

**Review by lubeda — APPROVED** [review]

**Pull request merged**
