### PR TITLE
2023.9.1 Replace Time Date Text

### PR DESCRIPTION
**Pull request by trip5**
Perhaps you were thinking I wouldn't... but I did.  How do you feel about this?  (My Korean wife loves it.)

Korean Time

Replaces any text used by strftime in all 4 screens that show date or time functions (clock, date, icon clock, icon date).

Useable in the YAML as so (if it works with Korean, it should work with anything):
````
  replace_time_date_from: "AM PM Sun Mon Tue Wed Thu Fri Sat Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec"
  replace_time_date_to: "오전 오후 일 월 화 수 목 금 토 1월 2월 3월 4월 5월 6월 7월 8월 9월 10월 11월 12월"
````

A pre-release of the Koreanized font used in the above picture:
[8X Fonts (K TimeDate chars).zip](https://github.com/lubeda/EspHoMaTriXv2/files/12850209/8X.Fonts.K.TimeDate.chars.zip)

For a demonstration of the code:
https://onlinegdb.com/-Rg8UZN-8

Safety measures included in the python file to prevent users from making mistakes: it counts & check the number of words are equal and not more than 50 (the fixed size of the array), that both settings are included... and triggers a bool to leave the function unused if there was a problem.

I had to include 1 more dependency `#include <algorithm>` because `replace` was malfunctioning on the 1st character... in any case, it also uses `vector` so it should be faster.

In the future, I'll take a look and see if what I added here can be used to speed up the recent addition to the `weekdays` because I'm pretty sure that `GetWeekdayCharCount` and `GetWeekdayChar` can be optimized using `vector`.

### CODE REVIEW

**Comment by lubeda** [comment]
I didn't check this PR in total, but some lines of documentation in the readme or the wiki are missing.

**Comment by trip5** [comment]
Indeed, you're right.  I trusted Visual Studio to do its thing and it didn't sync a few files.  I'll have to manually download them and put them back in after work...

**Comment by andrewjswan** [comment]
> A pre-release of the Koreanized font used in the above picture

Why make a separate font? TTF supports many languages, it would be more convenient and easier to have one font with everything you need.

**Comment by trip5** [comment]
Nope.  Not a special font.  Just added a few Korean characters to my Chunky8X as a personal test.  Figured I'd include that test font here.  There's already adjustments made to the characters with my wife's advice and consulting other pixel fonts online...

I think I misunderstood lubeda earlier.  I've made the wiki file for this function and cleaned up some other parts of the wiki... minor changes really.

**Comment by trip5** [comment]
Sorry this is typically me.  Too many commits.

**Comment by andrewjswan** [comment]
> Just added a few Korean characters to my Chunky8X as a personal test

I'll be waiting for those letters in the MatrixChunky font. :)

**Review by lubeda — APPROVED** [review]

**Pull request merged**
