### PR TITLE
added always_show_rl_indicators boolean

### PR DESCRIPTION
**Pull request by jfurtner**
Added config entry and changes to draw() function, just ifdef'd around current if clauses to match current behaviour by default.

I wanted to be able to show rl indicators on any screen (including clock/date).

### CODE REVIEW

**Comment by lubeda** [comment]
i check this in two weeks after my holiday

**Comment by dbuezas** [comment]
I initially thought the indicator was broken, it not showing on top of the clock was quite unexpected.
You may want to consider showing it everywhere by default :)

**Comment by lubeda** [comment]
Hi, i will take a look this weekend. But I think the left indicator is quite intrusive with icons, so I prefer my way. But there is general caveat in your pull request.

**Comment by lubeda** [comment]
Hi, i have problems in merging this PR because the diff of the ehmtx.cpp and the __init__.py don't show the differences. Instead, they seam to be a complete replacement of the original files.

**Comment by jfurtner** [comment]
Interesting. I’ll check, likely line end differences. On Jul 16, 2023, at 9:05 AM, LuBeDa ***@***.***> wrote:﻿
Hi, i have problems in merging this PR because the diff of the ehmtx.cpp and the init.py don't show the differences. Instead, they seam to be a complete replacement of the original files.

**Comment by jfurtner** [comment]
The diff shows the changes correctly. Now to figure out what settings I've got wrong in VS Code.

**Comment by lubeda** [comment]
is merged to develop

**Comment by jfurtner** [comment]
Thanks @lubeda

**Pull request closed without merging**
