### PR TITLE
2023.9.1-122: Change timestamp to milliseconds

### PR DESCRIPTION
**Pull request by andrewjswan**
The first draft, while it doesn't work yet, in theory should solve the problem https://github.com/lubeda/EspHoMaTriXv2/issues/122

### CODE REVIEW

**Comment by lubeda** [comment]
did you check the result? Is the transition between screens now better?

**Comment by andrewjswan** [comment]
@lubeda I'm obviously missing something, the screens switch either instantly or with a delay of a couple minutes until I realize where the error is.

Maybe look from the outside, a fresh perspective sometimes solves all problems. :)

**Review by lubeda — APPROVED** [review]

**Comment by andrewjswan** [comment]
Looks like I did, not sure about working on the 8266 (I can't test) but on the Esp32 (Ulanzi TC001) it works. Not much time has passed, but I have tested almost all modes.

**Comment by andrewjswan** [comment]
Uptime 20h +, not a single glitch... I like that. :)

**Pull request merged**
