### PR TITLE
2024.5.0: Add Flip Flop Clock mode

### PR DESCRIPTION
**Pull request by andrewjswan**

### CODE REVIEW

**Comment by andrewjswan** [comment]
```
ehmtxv2:
  id: rgb8x32
...
  advanced_clock: true
  flip_flop_clock: true
```

**Comment by trip5** [comment]
Does this flip the clock 180 degrees?  If yes, I believe there's already a solution for that built into ESPHome display functions (I remember asking about it before but I stopped using it).

**Comment by trip5** [comment]
Oh, found it: https://github.com/lubeda/EspHoMaTriXv2/wiki/rotate-ULANZI-display-180-degrees

**Comment by andrewjswan** [comment]
Every time the clock numbers change, the old one moves down and a new one comes to take its place, quite funny.

**Comment by trip5** [comment]
Lol is that right?  I didn't use any animation when I tried it, just the fade transition.  I would have thought the screen flip happened at a lower level but... haha.  Just haha.

BTW I haven't had time to update my clocks in a few months.  I've been hard at work on some e-ink projects... the wife was getting annoyed at all the Home Assistant notifications on the clock, interrupting the stuff that's actually useful to her... so...  I'll get around to it.  I expect I have a learning curve to go when I finally do run the update and get all the new schnick-schnack (razzle-dazzle in English whatever the German is).

**Comment by lubeda** [comment]
This is nice, the first schnick-schnack I really like!

**Pull request merged**
