### PR TITLE
2023.9.1: Add text progress screen

### PR DESCRIPTION
**Pull request by andrewjswan**
https://github.com/lubeda/EspHoMaTriXv2/issues/143

### CODE REVIEW

**Comment by chertvl** [comment]
it seems very accurate
useful for me, thank you!

**Review by lubeda — APPROVED** [review]

**Comment by lubeda** [comment]
Why text and value? if text and value are long the overwrite each other? I think value is enough or text should scroll.

**Comment by andrewjswan** [comment]
> Why text and value?

Text on left, value on right ...


> if text and value are long the overwrite each other?

Yes

> I think value is enough or text should scroll.

Well, I did not want to make the text scrolling, but it is generally not difficult, but you need to write a calculator to understand the width of the value, and what if the width of the value will be 30 characters? 
And so let the user decide for himself how it is more convenient for him.

**Comment by lubeda** [comment]
HI, I'm not sure what's the best way. Due to the limited screen space there are always some draw backs. Without scrolling I think the best way is to check the pixels for value and text if the fin in 32 pixel display both, if don't display only the text because the value is indicated somehow with the bar.

A limitation based on character count is quite random.

**Comment by andrewjswan** [comment]
I don't mind, but it seems to me that this is such a specific screen that those who will use it will be able to define and shorten the text and value so that everything is on the screen. But I like your idea, it won't be a mess, just text.

**Comment by chertvl** [comment]
> But I like your idea, it won't be a mess, just text.

I agree.
For my tasks (4symb text) + (3symb value + '%') is enogh, as I asked in issue.
Any improvements I support.

**Pull request merged**
