### PR TITLE
2024.12.1: Removed unused components, corrected version

### PR DESCRIPTION
**Pull request by andrewjswan**

### CODE REVIEW

**Comment by andrewjswan** [comment]
@lubeda Do you have any comments?

**Comment by lubeda** [comment]
Why did you comment all "EHMTXv2_MULTICOLOR_TEXT" out instead of deleting them?

**Comment by andrewjswan** [comment]
> Why did you comment all "EHMTXv2_MULTICOLOR_TEXT" out instead of deleting them?

As far as I remember, it was an attempt to remake the current version. I decided to leave it, but make it so that it does not get into the firmware. Well, so as not to do it again in the future. If you do not need it, you can delete it, or let me know, I will delete it.

**Comment by andrewjswan** [comment]
I cleanup code...

**Comment by andrewjswan** [comment]
@lubeda Hi!
I didn't delete `multicolor_text` , I left it and it should work, I only deleted unused procedures (which I didn't add and they weren't used in the code).
But in **2024.12.0** `multicolor_text` is there, and in **2024.12.1** it's gone... How to get it back?

**Comment by andrewjswan** [comment]
https://github.com/lubeda/EspHoMaTriXv2/compare/2024.12.0...2024.12.1

**Comment by andrewjswan** [comment]
I make new PR
https://github.com/lubeda/EspHoMaTriXv2/pull/264

**Pull request merged**
