### PR TITLE
2023.9.1-PR116: Move sbitmap to EHMTX::queue

### PR DESCRIPTION
**Pull request by andrewjswan**
https://github.com/lubeda/EspHoMaTriXv2/pull/116#issuecomment-1774571035

### CODE REVIEW

**Comment by andrewjswan** [comment]
Didn't notice the increase in size...
```
RAM:   [=         ]  14.4% (used 47152 bytes from 327680 bytes)
Flash: [========= ]  86.2% (used 1581913 bytes from 1835008 bytes)
```

**Comment by andrewjswan** [comment]
4 days, no problems, everything is stable in all modes.

**Comment by lubeda** [comment]
This is a waste of RAM if you are using other components like a microphone or other components, this isn't good. I agree with having more dynamic icons would be nice, but not like this. Perhaps you can set the amount of sbitmaps at compile time and introduce a new screen_type `bitmapx_screen => {"bitmap_slot","[0,4523,0,2342,0,..... (64 values 16bit values rgb565)]", "lifetime", "screen_time"}`, this is an acceptable compromise (I think).

**Comment by andrewjswan** [comment]
I haven't noticed any problems, I have WEB enabled, and other additional sensors, no memory issues.

**Comment by andrewjswan** [comment]
To save memory, it is necessary to make a dynamic queue and a dynamic array of icons, then when adding an entity will be created and added to the required list, when it is not needed memory is released.
But it is better to do it in Version 3. Here this variant works perfectly well.

**Comment by andrewjswan** [comment]
@lubeda We can try to make this array dynamic:
```
Color* sbitmap;
```
and allocate memory as needed:
```
if (sbitmap== NULL) 
{
  sbitmap= new Color[64];
}
```
But I don’t yet know where to properly clean it. When a screen is removed from the queue.

**Comment by andrewjswan** [comment]
I changed sbitmap to a dynamic array, checked it, it works.

**Comment by andrewjswan** [comment]
About three to five screens a day. Everything's stable. No degradation has been noticed.

**Comment by andrewjswan** [comment]
Conflict resolved.

**Comment by andrewjswan** [comment]
Thanks

**Pull request merged**
